app_name = "bingo"

# possible values: DEBUG, INFO, SUCCESS, WARNING, ERROR, FATAL
log_level = "DEBUG"

[server]
ip = "127.0.0.1"
port = 8888
user = "dj"
password = 123456
database = "awesome"

[redis]
ip = "127.0.0.1"
port = 7381